export const SERVICE_PREFIX='MS/FAQS/1.0';
export const SERVICE_VERSION='1.0';
export const SERVICE_DESCRIPTION = 'Realiza CRUD de Faqs y realiza la integracion con Groq (compatible con OpenAI)';
export const END_POINT_METHOD_FAQ = 'Faq'
export const ALLOWED_TEXT_REGEX = /^[\p{L}\p{N}\p{P}\p{Zs}¡¿@]+$/u;
export const CODE_200 ='OK';
export const MSG_200 = 'Operación realizada con éxito';
export const CODE_400 = 'ERROR_REQUEST';
export const MSG_400 = 'Error en la validación de datos';
export const CODE_500 = 'ERROR_INTERNAL';
export const MSG_500 = 'Error Interno del Servidor';
export const CODE_504 = 'ERROR_TIMEOUT';
export const MSG_504 = 'La Operación ha alcanzado el tiempo máximo de espera';
export const CODE_404 = 'ERROR_NOT_FOUND';
export const MSG_404 = 'Recurso no Existe';
export const LEGACY_MONGODB = 'MongoDB';
export const LEGACY_GROQ = 'Groq';
export const LEGACY = 'Cloud';
export const SERVICE_NAME ='msfagback';